name: New Release and tag
on:
  workflow_dispatch:
    branches: [master]
jobs:
  create-tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Get last merged PR
        id: last-merged-pr
        run: |
          PR_NUMBER=$(gh pr list --base master --state merged --limit 1 | awk '{print $1}')
          PR_TITLE=$(gh pr view $PR_NUMBER --json title -q '.title')
          read -r first_word second_word <<< "$PR_TITLE"
          if [ "$first_word" != "Release" ]; then
            echo "Error, the last PR merged in master ($PR_TITLE) is not a release, end of workflow. "
            exit 1
          fi
          echo "::set-output name=new_tag::$second_word"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the latest tag
        id: latesttag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Generate changelog
        id: changelog
        run: echo "::set-output name=commits::$(git log ${{ steps.latesttag.outputs.tag }}..HEAD --oneline)"

      - name: Create new tag
        run: git tag ${{ steps.last-merged-pr.outputs.new_tag }}

      - name: Push tags
        run: git push origin --tags

      - name: Display last merged PR title
        run: echo "The neeew tag is '${{ steps.last-merged-pr.outputs.new_tag }}'"

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.last-merged-pr.outputs.new_tag }}
          name: Release ${{ steps.last-merged-pr.outputs.new_tag }}
          body: ${{ steps.changelog.outputs.commits }}
