name: New Release and tag
on:
  workflow_dispatch:
    branches: [master]
jobs:
  create-tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Get last merged PR
        id: last-merged-pr
        run: |
          PR_NUMBER=$(gh pr list --base master --state merged --limit 1 | awk '{print $1}')
          PR_TITLE=$(gh pr view $PR_NUMBER --json title -q '.title')
          read -r first_word second_word <<< "$PR_TITLE"
          if [ "$first_word" != "Release" ]; then
            echo "Error, the last PR merged in master ($PR_TITLE) is not a release, end of workflow. "
            exit 1
          fi
          echo "::set-output name=new_tag::$second_word"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new tag and push it
        run: | 
          git tag ${{ steps.last-merged-pr.outputs.new_tag }}
          git push origin --tags
      
      - uses: johnyherangi/create-release-notes@main
        id: create-release-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.last-merged-pr.outputs.new_tag }}
          release_name: Release ${{ steps.last-merged-pr.outputs.new_tag }}
          body: ${{ steps.create-release-notes.outputs.release-notes }}
