name: Automated Release and PR
on:
  push:
    branches:
      - master
  workflow_dispatch: # Trigger manually 
    branches: [master] # Branch on which the workflow will run 

jobs:
  release-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: 'false'

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Release ${ { steps.changelog.outputs.tag }}'
          commit-message: 'Create new release ${ { steps.changelog.outputs.tag }}'
          branch: 'dev'
          body: 'This PR is auto-generated for the new release.'

