name: Release # Workflow name displayed on GitHub 
on:
  workflow_dispatch: # Trigger manually 
    branches: [master] # Branch on which the workflow will run 
jobs:
  new-release: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v3 # Checkout our working repository 
      - name: Conventional Changelog Action
        id: changelog 
        uses: TriPSs/conventional-changelog-action@v3 
        with: 
          github-token: ${{ secrets.github_token }}
          output-file: "false"
      - name: Create Release # This action will create the actual release 
        uses: actions/create-release@v1 
        if: ${{ steps.changelog.outputs.skipped == 'false' }} 
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with: 
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Automated PR Dj'
          commit-message: 'Update data'
          branch: 'automated-pr-branch'
          delete-branch: true
          body: 'This PR is auto-generated by the create-pull-request action.'
