name: Automated Release and PR
on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch: # Trigger manually 
    branches: [master] # Branch on which the workflow will run 

jobs:
  release-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Get the latest tag
        id: gettag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Show the latest tag
        run: echo "The latest tag is ${{ steps.gettag.outputs.tag }}"
